version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

networks:
  db:
    driver: bridge